




== Introduction

=== Technology and the Humanities
My interest for the purpose of the field prelim is to investigate how information technology affects scholarly practice in the humanities. Just as information technology has affected business, education, and science, it has affected the humanities for decades. The phenomenon of technological change has been extensively studied by HCI, CSCW, Sociology and Organizational Studies, my hope is to bring insights from these domains to bare upon the so called “crisis in scholarly publishing.”

Humanists, like scientists, gave been actively discussing and passionately debating the meaning information technology and its relation to their domain. As it has with the sciences, computational technology opens  new research questions, data sets, modalities of publication, and fundamentally different forms of scholarly collaboration. In short, information technology affords an entirely new set of scholarly practices previously inconceivable. 

At the same time, untried or experimental practices are not necessarily meaningful as scholarship in traditional humanist disciplines. Just because something is technically possible, does not mean it is socially possible (and vice versa). Historians can self-publish their manuscripts as kindle books, or disseminate their ideas on blogs, but this subversion of existing the sociotechnical infrastructure (ex: peer review and scholarly publishing) does not always “count” in the eyes of a tenure review board (at least not yet). The complex relation between the activities technology enables and the conception or perception of those activities by a community or social world is my theoretical interest.

.Topology of Impact
The technological impact upon the humanities can be crudely divided into three areas: research, teaching, and publication.

Computational technology affects humanist research in a multitude of ways, from the mundane (such as reading books on the iPad instead of print) to the grandiose (large scale collaborations and research centers tackling the grand challenges of humanist inquiry). Digitized data enables us to ask research questions previously thought impossible (i.e. "The rise and fall of a specific word in the corpus of ALL Victorian literature."). Infrastructure enables researchers to work together across space and time, collaborating and asking questions much larger than they would have or could have alone. Not only do humanist scholars from around the world work together, they collaborate with researchers from different disciplines. GeoHistory has recently emerged as a mash-up of geography and history, making possible enterprises such as Stanford's Spatial History project.[1] 

Second, information technology raises fundamental questions about humanitarian pedagogy. What are the baseline skills necessary to be a humanist in the digital age? Knowledge of the capabilities of technical and quantitative methods shapes a scholar’s understanding of the possible. Knowing, on a very pragmatic level, the strengths and limitations of natural language processing or programmatic data manipulation affects how you ask research questions. Where are students going to obtain technical skills? Could programming become a necessary requirement to be a digital humanist? Or, should humanists instead collaborate with technically inclined researchers in other fields? Large-scale collaboration in the humanities will require scholars from radically different domains, both within and outside the humanities, to work together. In this case, they should learn to how to effectively communicate with programmers and technologists. Interdisciplinary collaboration requires common ground between the scholarly communities of practice. Where humanities scholars learn these technical and communicative skills is an open question, especially when thinking about the future of the field.

Finally, information technology has deeply affected the institutions of scholarly publishing and communication in the humanities. Electronic publishing raises a series of difficult questions regarding the archiving of scholarly publications and data. How does one publish and distribute a GeoHistorical interactive map? What are long-term prospects for interactive and multimodal knowledge artifacts? What constitutes “data” in the humanities? Information communication technology has rendered visible the invisible college of communication in the humanities. Blogs, twitter, and mailing lists have given humanities scholars the opportunity to enthusiastically connect and share ideas with incredibly rapid feedback cycles. Furthermore, we now have records of these conversations, from the Humanist mailing list started in 1987 to the "#thatcamp" twitter backchannel begging the question “what can we do with these records?” Furthermore, questions of intellectual property and open access to scholarly output loom over the entire system of publishing, both today and into the future.

The scholarly presses, a vital component of the humanitarian institutional reward structure, are in crisis. The current system of publishing obscure manuscripts for tenure track scholars is claimed to be unsustainable. The presses are under enormous pressure to do more with less. Digital publishing technology affords the possibility of fundamentally new modalities of disseminating knowledge, but the challenges are well beyond the technical. The social and academic institutions must be willing to accept change, a tall order for some scholarly communities who still insist on print publications and a book (or two) for tenure. Institutional habits and routines, especially those of peer review and tenure, restrain the adoption of technological practice, as they should, for too radical a change might throw the baby out with the bath water.

.Electronic Publishing
For the purposes of the field prelim, I am interested in examining how theories of situated action, communities of practice, organizational routine and activity move us beyond techno-utopian ruminations of electronic publishing’s technological affordances, and incorporate sociality into the process of design for scholarly publishing. Why publishing? I am personally attracted to this area because, in my view, it faces both theoretical and practical challenges. Scholarly publishing is directly connected to structures of scholarly communication, peer review, and perhaps more indirectly to research. Research needs to be published, right? Well, what does "published" really mean? What counts in the academic promotion systems shapes the kinds of research and the kinds of scholarly contributions that can be made. Digital technology affords unfamiliar forms of publishing that challenge existing social-technical institutionalization. Case and point is Kathleen Fitzpatrick new book "Planned Obsolescence,"[2] which has been "published" for free online in its draft form and will be published as a physical book later this year. Fitzpatrick, who interestingly has just become head of the Modern Language Association's Office of Scholarly Communication in part no-doubt because of her book, has critically examined the practice of scholarly publishing both theoretically, in the content of the book, but also practically in the modality in which she has pursued its dissemination. Using an online publishing platform called CommentPress[3] she published the book’s content as she wrote it and openly accepted comments from interested readers. While this may be radical in the world of scholarly book publishing, it is old news to the professional programming community. Publishers of technical books like O’Reilly and Manning have been putting out (and even charging for) beta copies and allowing comments for years, others have been publishing under open licenses[4] making the content available for free, both as in speech AND as in beer.

We can not, and should not, deny the impact that technology has had upon the publishing world writ-large, but at the same time we must be careful not to adopt a deterministic attitude in how technology affects social practice. This field prelim will explore how the design of digital publishing technologies effects the interaction cycle between social practices & communities as they orbit around them. I think of this phenomenon as a flavor of what Ackerman called the “social-technical gap,” the “divide between what we know we must support socially and what we can support technically.”(2000) This is the gap between the rigid and inflexible operation of technological systems and the richly contextualized, fluid, and flexible practices of social worlds.  In scholarly publishing, I see a socio-technical gap that I characterize as “the divide between what we know is possible technically and what is acceptable socially.” Both flavors of the gap are fundamentally about the social and technical practices that reciprocate in a mutually constitutive relation;[5] I call this “Ackerman’s Aphorism” and it is my prelim’s fundamental principal.

=== Engaging the Literature
This prelim falls into four main components. A section about the Digital humanities that lays out a working definition; a section about scholarly publishing, of which monograph publishing in the digital humanities is my specific interest; a section I call "Situated Practice" which bring together several theories of work-as-practice in an effort to better understand the what I am calling the "practice of new digital publishing."

.Digital Humanities / Humanities Computing
This section will be an introduction and discussion of the Digital Humanities. It will draw from the digital humanities/humanities computing (DH/HC) literature (ex. the Blackwell Companion series and the ?????) and will do a little bit of boundary defining work guided by sociological literature about scholarly communities (namely Chris Kelty's "recursive communities" and Andrew Abbot's "Chaos of Disciplines" [todo: justify these choices. scope, I'm not conducting an institutional analysis]). 
 
.Scholarly Publishing
This section has two parts, the first is a discussion of scholarly publishing in practice. The practices of scholarly publishing are varied and not all are within the scope of this prelim. My focus here is specifically on scholarly monograph/book publishing in the digital humanities. What literature I can find about the practices of scholarly monograph publishing will be reviewed, but it is my hunch there is a gap in this literature (to be explored in the research design section). While this prelim is not a thorough discussion of the book as an object in and of itself, I will need to dip my toes into the "Nature of the Book"(Johns), "Books in the Digital Age" (Thompson). I will also briefly review several explorations of new publishing modalities, for example Fitzpatrick's study of CommentPress, Kirchenbaum's "Mechanisms."  This flows into the second part; the debate around the "crisis of scholarly publishing." Fitzpatrick's "Planned Obsolescence" provides a cornerstone summary, and will be further fleshed out by prominent essays (Unsworth, Greenblatt)  and white papers (Harley, Brown). The final part of this section

.Situated Practice




and briefly discusses the concept of technical affordances to help understand how digital technology presents technical solutions to the problems facing scholarly publishing. However, technical solutions and their afforded possibilities cannot fully "solve" the publishing challenges faced by the humanities. Affordances, in both publishing theory and practice, neglects to account for the challenge of social acceptability faced by new sociotechnical practice in scholarly publishing. There exists a potentially definitional set of acceptable action/activity/routines/practices that protect and preserve the humanities as a social institution/organization/community. How do these practices along with their accompanying social identities change in the face of destabilizing technology?
The relation between sociality and technology is complicated and has been extensively explored in the academic literature. For second section of the prelim, I will be examination the sociotechnical relations between the electronic publishing and the humanities through the lens of activity theory, communities of practice, situated action, and organizational routine. The intersection of these four bodies of literature will provide a baseline for the development of an analytical framework I hope to deploy in the analysis and design of publishing tools, systems, and infrastructure. A key feature of this framework, which is present in the diagram above and will be further fleshed out in the prelim, is the mutual relation between social institutions/organizations/sociality/community and their actions/routines/activities/practice. I posit there is a mutual reinforcement or feedback cycle between social groups and the practices in which they engage. Diagrammatically, social groups shape and constrain practice and activity, which in turn forms or reinforces social groups. How this cycle orbits around technology and its relation to sociotechnical change is fundamental to this investigation.
The third and final section of this project will be a research proposal that integrates the analytical framework with theories of design. Drawing on the framework from section two and the literature on sociotechnical design, this section would plan a case study that examines the infrastructure, practice, and communities shaped and served by electronic publishing technology. One potential for the case study is MPublishing, the University of Michigan's scholarly press. MPublishing is heralded in the community as pushing the boundaries of scholarly publishing practice. They have embraced digital technology and are actively exploring new ways to disseminate academic knowledge. The proposed case-study would use the framework developed in section two to better understand how MPublishing’s technological initiatives become acceptable (or not acceptable) scholarly publishing, how they shape and are shaped by the community they serve, and finally use these insights to inform the design of new infrastructure and practice in academic publishing.










DH/HC is a coin - Methods on one side, sources on the other
I frame DH/HC as a doubles sided coin, with new methodologies on one side and new sources/research objects on the other.  This conceptual frame reveals the true object of my prelim, the rim of the coin or the publication knowledge in the digital humanities.
	My focus is on neither side, rather I am interested in the rim of the coin:
		The dissemination of DH/HC knowledge.
		Publishing in the Digital Humanities.


What do publishers do in _practice_?
	The interaction between scholars and publishers, focusing on the process of publishing a monograph. 
	The Columbia Online Books Evaluation Project
		http://www.arl.org/resources/pubs/scat/mandel-2.shtml


Capture the 20+ year debate about digital technology and monograph publishing. Why, in the face of multimodal technology does the the book/monograph persist? Why haven't things changed (or haven't changed fast enough)? Why do scholars create structures like PressForward? 


I am bringing a new angle/ theoretical perspective to this discussion. I wish to bring to bear theories of work-practice, to better understand the practical "mechanisms of new digital scholarly publishing."