=== Blather

and briefly discusses the concept of technical affordances to help understand how digital technology presents technical solutions to the problems facing scholarly publishing. However, technical solutions and their afforded possibilities cannot fully "solve" the publishing challenges faced by the humanities. Affordances, in both publishing theory and practice, neglects to account for the challenge of social acceptability faced by new sociotechnical practice in scholarly publishing. There exists a potentially definitional set of acceptable action/activity/routines/practices that protect and preserve the humanities as a social institution/organization/community. 





A key feature of this framework, which is present in the diagram above and will be further fleshed out in the prelim, is the mutual relation between social institutions/organizations/sociality/community and their actions/routines/activities/practice. I posit there is a mutual reinforcement or feedback cycle between social groups and the practices in which they engage. Diagrammatically, social groups shape and constrain practice and activity, which in turn forms or reinforces social groups. How this cycle orbits around technology and its relation to sociotechnical change is fundamental to this investigation.
The third and final section of this project will be a research proposal that integrates the analytical framework with theories of design. Drawing on the framework from section two and the literature on sociotechnical design, this section would plan a case study that examines the infrastructure, practice, and communities shaped and served by electronic publishing technology. One potential for the case study is MPublishing, the University of Michigan's scholarly press. MPublishing is heralded in the community as pushing the boundaries of scholarly publishing practice. They have embraced digital technology and are actively exploring new ways to disseminate academic knowledge. The proposed case-study would use the framework developed in section two to better understand how MPublishing’s technological initiatives become acceptable (or not acceptable) scholarly publishing, how they shape and are shaped by the community they serve, and finally use these insights to inform the design of new infrastructure and practice in academic publishing.




Digital technology affords unfamiliar forms of publishing that challenge existing social institutions. Case and point is Kathleen Fitzpatrick new book "Planned Obsolescence," which has been "published" for free online in its draft form and will be published as a physical book later this year. Fitzpatrick, who interestingly has just become head of the Modern Language Association's Office of Scholarly Communication, has critically examined the practice of scholarly publishing both theoretically, in the content of the book, and practically in the modality in which she has published the book. Using an online publishing platform called CommentPress she published the book’s content as she wrote it and openly accepted comments from interested readers. While this may be radical in the world of scholarly book publishing, it is old news to the professional programming community. Publishers of technical books like O’Reilly and Manning have been putting out (and even charging for) beta copies and allowing comments for years, others have been publishing under open licenses making the content available for free, both as in speech AND as in beer. This begs an interesting question, why are socio-technical publishing practices common, almost to the point of banel, in prevalent in the technical community so astonishing and groundbreaking in the scholarly publishing community?






DH/HC is a coin - Methods on one side, sources on the other
I frame DH/HC as a doubles sided coin, with new methodologies on one side and new sources/research objects on the other.  This conceptual frame reveals the true object of my prelim, the rim of the coin or the publication knowledge in the digital humanities.
	My focus is on neither side, rather I am interested in the rim of the coin:
		The dissemination of DH/HC knowledge.
		Publishing in the Digital Humanities.


What do publishers do in _practice_?
	The interaction between scholars and publishers, focusing on the process of publishing a monograph. 
	The Columbia Online Books Evaluation Project
		http://www.arl.org/resources/pubs/scat/mandel-2.shtml


Capture the 20+ year debate about digital technology and monograph publishing. Why, in the face of multimodal technology does the the book/monograph persist? Why haven't things changed (or haven't changed fast enough)? Why do scholars create structures like PressForward? 


I am bringing a new angle/ theoretical perspective to this discussion. I wish to bring to bear theories of work-practice, to better understand the practical "mechanisms of new digital scholarly publishing."