=== Notes from Finn Meeting (friday 30sept11)

I think I have devised an argument and a structure for that argument. The argument is that the digital humanities and the crisis in scholarly publishing are both aspects of a larger shift and restructuring in what I am calling the "Regime of accountability" that constitutes knowledge in the academy. Regime of acocuntabilt is my adaption of ethnomethodological accounts to be applied to the context of humanistic monograph production. 


*  Introduce Regime of accountability asa working concept. Need to explain ethnomethodological account and show how scholarly monographs are "accounts" of a social situation. In our case the social stituation is humanists scholarly practice. It is through the production of accounts that knowledge is constituted. It is how we take an idea or concept from our head and make it "count," make it peer-reviewed, make it cite-able, make it something other people can "use" (from a rhetorical perspective). Scholarly publishing *is* the regime of accountability for the humanities. 
*  Introduce the "Mechanisms of scholarly publishing." Talk about the practice of scholarly publishing, perhaps focusing on how  it was practiced historically. Nature of the book? What else goes here? One of the key arguments to be made here is how there is a "certain way of doing things," a sequence of actions must be carried out such that knowledge can be constituted. Without adherence to that sequence, knowledge cannot be constituted. This has been exhaustively studied in science. The Pulsar paper is a good example of how the on-the-ground work is done and then accounted for *and* how there inevitably exists a gap between the local situated  practice and the account of that practice. What is missing are some studies of humanists doing this kind of work. I assume here that they must produce accounts of their locally situated work just like scientists. So....if practice is what constitutes knowledge within a regime of accountability, i.e. scholarly publishing, then what happens when a new forms of practice enter the equation/ jump in the water?
*  Introduce DH, not only as a transformation in practice, but as an activist movement (Pannapacker 2011) engaged in an active effort to reconfigure the "regime of accountability." It is interesting, that many of the articles and commentaries I read about DH, are not simply about DH, they are about the academy as a whole. As I argue about, practice is deeply connected to the constitution of knowledge, practice coupled with publishing.  Any regime of accountability has a certain set of expected sequences of practice that must be enacted so that the account can be constituted. Scholarly publishing has historically "demanded" the production of a scholarly monograph (or two) to "support," from a social perspective, the constitution of humanist knowledge. We can know this, we can claim this, because of the publish-a-book requirement to achieve tenure, and I suppose we assume that tenure is given to those who produce knowledge (perhaps a flawed assumption, needs to be worked out. Publishing thus is a vital aspect of constituting humanistic knowledge. It would be a shame if scholarly publishing, which is the regime of accountability for humanists and thus the basis of constituted knowledge, were to be threatened.
*  Introduce the crisis in scholarly publishing as an indication that the current regime of accountability is unstable (note, I am not making any claims as to why, although I should make a nod towards the standard story about commercial publishers (summarized in stage five book publishing), I am also making an implicit nod towards digital humanities. I am not claiming DH has caused the crisis in scholarly publishing, however, I am claiming that DH is perhaps in part enabled by the crisis. There is blood in the water so to speak.) Before, the "work" of presses was their editorial abilities. it was their curation that distinguished them. They were gatekeepers. This is no longer true, all of the other work that goes into publishing, editing, printing, marketing, etc. The transaction costs are now not consistent across presses. the commercial presses have the advantages of economies of scale, but for non-profit academic presses, they don't have those economies of scale (i think of economy not as $$$, but as work). They are now competing in bloody waters were there are radically different sized sharks. It used to be that every shark was the same size, not any more. 
	- new technology can help release the pressure, technology can help reduce the transaction costs of being a publishing (to an extent). Yet, new technology cannot simply be used without commensurate social acceptance. Ackerman's Aphorism.
*  Argue the configuration of the "old system" of scholarly publishing existed as a  n information management device (Blair 19??). Now the "phenomenological conservatives" (to borrow Finn's phrasing) are freaking out because all this new technology is going to create "more work" for them. This is also consistent with the re-configuration that scholarly publishing is undergoing. The new system is pushing off work (especially editorial work? What kind of work is being moved?) on-to the scholars themselves (delegation as a solution to the transaction cost dissimilarity.
*  As an information management problem, the solution lies in time. It is going to take time for a new set of habits and routines to emerge that alleviate the cognitive load (on all participating actors) so that we do not feel overwhelmed by the new praxis. 







=== Blather

and briefly discusses the concept of technical affordances to help understand how digital technology presents technical solutions to the problems facing scholarly publishing. However, technical solutions and their afforded possibilities cannot fully "solve" the publishing challenges faced by the humanities. Affordances, in both publishing theory and practice, neglects to account for the challenge of social acceptability faced by new sociotechnical practice in scholarly publishing. There exists a potentially definitional set of acceptable action/activity/routines/practices that protect and preserve the humanities as a social institution/organization/community. 





A key feature of this framework, which is present in the diagram above and will be further fleshed out in the prelim, is the mutual relation between social institutions/organizations/sociality/community and their actions/routines/activities/practice. I posit there is a mutual reinforcement or feedback cycle between social groups and the practices in which they engage. Diagrammatically, social groups shape and constrain practice and activity, which in turn forms or reinforces social groups. How this cycle orbits around technology and its relation to sociotechnical change is fundamental to this investigation.
The third and final section of this project will be a research proposal that integrates the analytical framework with theories of design. Drawing on the framework from section two and the literature on sociotechnical design, this section would plan a case study that examines the infrastructure, practice, and communities shaped and served by electronic publishing technology. One potential for the case study is MPublishing, the University of Michigan's scholarly press. MPublishing is heralded in the community as pushing the boundaries of scholarly publishing practice. They have embraced digital technology and are actively exploring new ways to disseminate academic knowledge. The proposed case-study would use the framework developed in section two to better understand how MPublishing’s technological initiatives become acceptable (or not acceptable) scholarly publishing, how they shape and are shaped by the community they serve, and finally use these insights to inform the design of new infrastructure and practice in academic publishing.




Digital technology affords unfamiliar forms of publishing that challenge existing social institutions. Case and point is Kathleen Fitzpatrick new book "Planned Obsolescence," which has been "published" for free online in its draft form and will be published as a physical book later this year. Fitzpatrick, who interestingly has just become head of the Modern Language Association's Office of Scholarly Communication, has critically examined the practice of scholarly publishing both theoretically, in the content of the book, and practically in the modality in which she has published the book. Using an online publishing platform called CommentPress she published the book’s content as she wrote it and openly accepted comments from interested readers. While this may be radical in the world of scholarly book publishing, it is old news to the professional programming community. Publishers of technical books like O’Reilly and Manning have been putting out (and even charging for) beta copies and allowing comments for years, others have been publishing under open licenses making the content available for free, both as in speech AND as in beer. This begs an interesting question, why are socio-technical publishing practices common, almost to the point of banel, in prevalent in the technical community so astonishing and groundbreaking in the scholarly publishing community?






DH/HC is a coin - Methods on one side, sources on the other
I frame DH/HC as a doubles sided coin, with new methodologies on one side and new sources/research objects on the other.  This conceptual frame reveals the true object of my prelim, the rim of the coin or the publication knowledge in the digital humanities.
	My focus is on neither side, rather I am interested in the rim of the coin:
		The dissemination of DH/HC knowledge.
		Publishing in the Digital Humanities.


What do publishers do in _practice_?
	The interaction between scholars and publishers, focusing on the process of publishing a monograph. 
	The Columbia Online Books Evaluation Project
		http://www.arl.org/resources/pubs/scat/mandel-2.shtml


Capture the 20+ year debate about digital technology and monograph publishing. Why, in the face of multimodal technology does the the book/monograph persist? Why haven't things changed (or haven't changed fast enough)? Why do scholars create structures like PressForward? 


I am bringing a new angle/ theoretical perspective to this discussion. I wish to bring to bear theories of work-practice, to better understand the practical "mechanisms of new digital scholarly publishing."