== free writing ==
====================
_make a list of all the important things I need need to make the case for this proposed research design. +
do it fast, free write +
what needs to be argued so that everyone agrees this is a good research proposal_
====================
    
What is the argument I want to make?
Well I want to say that there is a need for a research project that does a practice centric ethnography of scholarly publishing in the digital humanities. As Paul Conway has described it, there are two wheels of practice, that of the (digital) humanities scholars and that of the scholarly publishers. The site of intersection between these two wheels is my area of interest. But I am not simply interested in these spinning wheels alone, I want to investigate how technological change throws a wrench between these two wheels (gears?).

I believe that the theories and methods provided by social science, specifically the perspective afforded by situated work practice, will shed light on the question of why the practices of scholarly publishing manuscripts in the digital humanities is not adapting to technological change.

The "situated practice" literature is going to need to sharpen its focus. I need to show that it has informed the problem of adapting work practice in the face of new technology. Technomethodology? Suchman? I need to review Ackerman's Gap paper, that provides a nice review of "what CSCW knows". I should also go through the CSCW journal and conference backlog. Key off the term 'adaptation.'   

I need to do the same thing for the communities of practice literature. Is there anything that directly engages change in communities of practice? If I can't find anything to this effect it might be a reason to drop a substantial investment in CoP literature, although it definitely needs to be there.

It might be the case that the organizational routine literature might be _easier_ to bring to bear upon this particular problem. The org routine work specifically address the problem of (n)ever changing. The camp poplar grove is a good example. Practices are replicated, despite their underspecification. So then the question is how does technological work practice relate to organizational routine?

I need to demonstrate that the "situated practice" perspective (which is broadly construed to include ethnomethodological, situated action, communities of practice, org routine) can inform the broad problems of (n)ever change in the face of new technology. 

To do that do that, I need to demonstrate that there is a (n)ever change situation in scholarly publishing. I need to show how in the face of selection pressures from new technology (as well as a host of other sources) the practices of monograph publishing are not changing (or perhaps more accurate that they aren't changing fast enough, or in the expected direction). The production of the  humanities monograph is the focus. 

To do that, I need to do some descriptive work, looking at the scholarly practice of monograph creation. To do this I will focus on the digital humanities. Digital humanities/humanities computing's changing practices are affording new modalities for scholarly dissemination. New research practices are demanding commensurate change in the models of dissemination. This is imposing a selection pressure upon the scholarly publishers.

What might the research design going to look like?
The site of the study will be MPublishing. I have already well established relationships with several people who work at MPUb and they are very enthusiastic about my work in this area. They are doing a lot of boundary work, trying to push the envelope of new digital scholarly publishing, while at the same time they maintain their traditional scholarly imprints [note: need to look up the term imprint to find out exactly what it means and how to use it.]. MPublishing would be the site of the research project. I will conduct interviews with folks who work at Mpub, and with scholars who have worked with mpub to publish their books. While mpub does extensive work on journal publishing, specifically the journal of electronic publishing, that is not going to be the primary focus of the study. Above and beyond the book and journal publishing, mpub is doing a lot of digital publishing work. This works falls into a broad spectrum that is difficult to classify. Some examples are Wordpress and CommentPress sites that resemble blogs or books with paragraph level comment features. 
I recently attended a meeting between folks from mpublishing and the sweet land writing center. They are in the early initial planning stages of a collaborative project (described below). One of the challenges I observed in the meeting was figuring out what the project _is_ and who was going to do what. Sweetland has a grand, but also highly ambiguous, vision and they wanted to know what services mpublishing can provide too help them achieve that vision(also how much it was going to cost). It is difficult for mpub to articulate what services they provide (as well as cost) for projects  when there is little precedent to utilize as a base. For all parties involved are doing something that in some respects _has never been done before_.
	The project began as a curated conference proceedings of the recent Computers and Writing 2011 conference held at the University of Michigan. I attended the conference and helped video record a bunch of the sessions. Additionally, I wrote a series of scripts that downloaded all of the tweets from the conference (or at least a good chunk of them). The idea of combining a more formal release of conference proceedings combined with the grey literatures (blogs, tweets, video and photos) generated by folks at or around the conference has been kicked around by the me and the sweet land folks. It has also been at the center of discussions about a larger and more ambitious collaboration between sweetland and mpublishing. The broader project, which does not have boundaries, is described as a general online resource and community for "digital writing." As this project matures, and incorporates the content we produced from the Computers and Writing conference, I think it will represent one of these new kinds of digital publishing projects that fall into this complicated spectrum. Observing this project, as well as participating directly, would be an excellent study in the complications facing the practice of new digital publishing. The one discussion revealed to me a lot about the practical challenges with new digital publishing. Sweetland, which represents the "scholars" so too speak, knows they want to do something different than typical conference proceedings. They want to, in my words, cultivate a scholarly community and defacto resource base around "Digital Writing" ( as I, semi jokingly, put it in the meeting, when someone googles for "digital writing" they want their site to show up on the first page). They kept asking the mpublishing representative "how much is this going to cost" which is a very difficult question for mpub to answer because the extent and scope of this thing is not clearly defined. Furthermore, mpub cannot fall back on previous examples because they have never done something like this before. They know they want to push forward in this area, they want digital publishing systems to be part of their service portfolio, but they are only starting to get their feet wet in this area. 



== goals
=== Chapter 1 - *Digital Humanities*  
show how new technology is fermenting (r)evolutionary change in the practices of humanities scholarship. To do this I will need to do a bit of definitional work, focusing on the debate on "Digital Humanities" vs "Humanities Computing." Both names represent the change that is affecting research, pedagogy, and the dissemination of knowledge in the humanities. While I will briefly touch upon the first two of these areas, my focus will be on the third. The dissemination of knowledge leads me into the next chapter, scholarly publishing.

=== Chapter 2 - *Scholarly Publishing*
show how evolved modalities of scholarly publishing coupled with these new forms of scholarship afforded by Digital Humanities/Humanities Computing are aggravating the "crisis in scholarly publishing." There are a multitude of facets to this crisis, from economic sustainability, to open access and intellectual property, to technical forms and modalities. 

=== Chapter 3 - *Situated Practice* 
show how studies of technological work practice have informed other domains with similar problems and shooter how it could be brought to bare in scholarly publishing.

=== Chapter 4 - *Research Design* 
As described above, the research would be a participatory investigation of digital publishing at MPublishing. Using concepts and techniques from the chapter on work studies and situated practice I will analyze a selection of projects, focusing in particular on traditional monograph publishing projects and on new digital publishing projects such as the one described above. 

A survey of Mpub's past, present and planned digital projects will be conducted in an attempt to construct a conceptual topology so that we can better understand the complicated spectrum that encompasses both traditional and digital work.